image: maven:3.9.9-eclipse-temurin-11
variables:
  TESTED_BRANCH: master
  TESTED_PARSER: jsoniq

workflow:
  name: 'testing ${TESTED_PARSER}-parser on ${TESTED_BRANCH} branch'

stages:
  - build
  - test
  - collect
  - analytics

build-job:
  stage: build
  script:
    - echo cloning ${TESTED_BRANCH}
    - git clone --single-branch --branch "${TESTED_BRANCH}" "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.inf.ethz.ch/gfourny/rumble.git" 
    - cd rumble
    - mvn clean compile assembly:single -quiet
    - cd ..
  artifacts:
    paths:
      - rumble/target

test-app:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
      mvn -Dtest=AppTest test -quiet || true;
      else
      mvn -Dtest=XQueryAppTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="AppTest" 
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-array:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=ArrayTest test -quiet || true;
      else
          mvn -Dtest=XQueryArrayTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="ArrayTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-fn1:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=Fn1Test test -quiet || true;
      else
          mvn -Dtest=XQueryFn1Test test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="Fn1Test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-fn2:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=Fn2Test test -quiet || true;
      else
          mvn -Dtest=XQueryFn2Test test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="Fn2Test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-map:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=MapTest test -quiet || true;
      else
          mvn -Dtest=XQueryMapTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="MapTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-math:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=MathTest test -quiet || true;
      else
          mvn -Dtest=XQueryMathTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="MathTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-misc:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=MiscTest test -quiet || true;
      else
          mvn -Dtest=XQueryMiscTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="MiscTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-op:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=OpTest test -quiet || true;
      else
          mvn -Dtest=XQueryOpTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="OpTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-prod1:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
      mvn -Dtest=Prod1Test test -quiet || true;
      else
      mvn -Dtest=XQueryProd1Test test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="Prod1Test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-prod2:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=Prod2Test test -quiet || true;
      else
          mvn -Dtest=XQueryProd2Test test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="Prod2Test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-ser:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=SerTest test -quiet || true;
      else
          mvn -Dtest=XQuerySerTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="SerTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

test-xs:
  stage: test
  dependencies:
    - build-job
  script:
    - if [ "$TESTED_PARSER" = "jsoniq" ]; then
          mvn -Dtest=XsTest test -quiet || true;
      else
          mvn -Dtest=XQueryXsTest test -quiet || true;
      fi
    - mvn exec:java@analytics-pre -Dexec.args="XsTest"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - analytics-pre/*.json
    reports:
      junit: target/surefire-reports/*.xml

spotless-check:
  stage: test
  dependencies:
    - build-job
  script:
    - mvn spotless:check

collect-artifacts:
  stage: collect
  dependencies:
    - build-job
    - test-app
    - test-array
    - test-fn1
    - test-fn2
    - test-map
    - test-math
    - test-misc
    - test-op
    - test-prod1
    - test-prod2
    - test-ser
    - test-xs
  script:
    - mkdir -p collected-artifacts
    - mvn compile
    - mvn exec:java@analytics-aggregation
    - cp -r target/surefire-reports collected-artifacts/
  artifacts:
    when: always
    paths:
      - collected-artifacts
      - analytics-results

plot:
  stage: analytics
  image: python:3.12
  dependencies:
    - collect-artifacts
  script:
    - pip install -r analytics/requirements.txt
    - python analytics/plot.py
    - echo TO SEE THE PLOTS, CLICK ON BROWSE ON THE RIGHT
  artifacts:
    when: always
    paths:
      - plots
      - analytics-results