package driver;

import java.nio.file.Path;
import java.nio.file.Paths;

public class Constants {
    public static final Path WORKING_DIRECTORY_PATH = Paths.get("").toAbsolutePath();

    public static final boolean USE_CONVERTED_TEST_SUITE = true; // use test suite generated by converter
    public static final String OUTPUT_TEST_SUITE_DIRECTORY = "Output_Test_Suite"; // path to test suite generated by
                                                                                  // converter
    public static final String CRASHED_TESTS_FILENAME = "Crashes.txt";
    public static final String SUCCESS_TESTS_FILENAME = "Success.txt";
    public static final String MANAGED_TESTS_FILENAME = "Managed.txt";

    public static final StringBuffer TEST_CASE_SB = new StringBuffer();
    public static final StringBuffer UNSUPPORTED_TYPE_SB = new StringBuffer();
    public static final StringBuffer CRASHED_TESTS_SB = new StringBuffer();
    public static final StringBuffer FAILED_TESTS_SB = new StringBuffer();
    public static final StringBuffer DEPENDENCY_TESTS_SB = new StringBuffer();
    public static final StringBuffer UNSUPPORTED_ERRORS_SB = new StringBuffer();
    public static final StringBuffer SKIPPED_TESTS_SB = new StringBuffer();
    public static final StringBuffer SUCCESS_TESTS_SB = new StringBuffer();
    public static final StringBuffer MANAGED_TESTS_SB = new StringBuffer();
    public static final StringBuffer BROKEN_TESTS_SB = new StringBuffer();

    public static final String[] supportedErrorCodes = new String[] {
        "FOAR0001",
        "FOCA0002",
        "FODC0002",
        "FOFD1340",
        "FOFD1350",
        "JNDY0003",
        "JNTY0004",
        "JNTY0024",
        "JNTY0018",
        "RBDY0005",
        "RBML0001",
        "RBML0002",
        "RBML0003",
        "RBML0004",
        "RBML0005",
        "RBST0001",
        "RBST0002",
        "RBST0003",
        "RBST0004",
        "SENR0001",
        "XPDY0002",
        "XPDY0050",
        "XPDY0130",
        "XPST0003",
        "XPST0008",
        "XPST0017",
        "XPST0080",
        "XPST0081",
        "XPTY0004",
        "XQDY0054",
        "XQST0016",
        "XQST0031",
        "XQST0033",
        "XQST0034",
        "XQST0038",
        "XQST0039",
        "XQST0047",
        "XQST0048",
        "XQST0049",
        "XQST0052",
        "XQST0059",
        "XQST0069",
        "XQST0088",
        "XQST0089",
        "XQST0094" };
}
